name: build-and-push
on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase repo for GHCR
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}/web:latest
            ghcr.io/${{ env.REPO_LC }}/web:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO_LC }}/web:cache
          cache-to: type=registry,ref=ghcr.io/${{ env.REPO_LC }}/web:cache,mode=max
          build-args: |
            BUILD_SHA=${{ github.sha }}
